export * from './lib/cmns-cmns-base-intf.module';
export type { ICmnsBairro } from './lib/cmns-bairro.interface';
export { CmnsBairroDto } from './lib/cmns-bairro.interface';
export type { ICmnsPais } from './lib/cmns-pais.interface';
export { CmnsPaisDto } from './lib/cmns-pais.interface';
export type { ICmnsUnidadeFederativa } from './lib/cmns-unidade-federativa.interface';
export { CmnsUnidadeFederativaDto } from './lib/cmns-unidade-federativa.interface';
export type { ICmnsLocalidade } from './lib/cmns-localidade.interface';
export { CmnsLocalidadeDto } from './lib/cmns-localidade.interface';
export type { ICmnsLogradouro } from './lib/cmns-logradouro.interface';
export { CmnsLogradouroDto } from './lib/cmns-logradouro.interface';
export type { ICmnsCargo } from './lib/cmns-cargo.interface';
export { CmnsCargoDto } from './lib/cmns-cargo.interface';
export type { ICmnsNacionalidade } from './lib/cmns-nacionalidade.interface';
export { CmnsNacionalidadeDto } from './lib/cmns-nacionalidade.interface';
export type { ICmnsOrgaoExpedidor } from './lib/cmns-orgao-expedidor.interface';
export { CmnsOrgaoExpedidorDto } from './lib/cmns-orgao-expedidor.interface';
export type { ICmnsProfissao } from './lib/cmns-profissao.interface';
export { CmnsProfissaoDto } from './lib/cmns-profissao.interface';
export type { ICmnsRamoAtividade } from './lib/cmns-ramo-atividade.interface';
export { CmnsRamoAtividadeDto } from './lib/cmns-ramo-atividade.interface';
export type { ICmnsTipoDocumento } from './lib/cmns-tipo-documento.interface';
export { CmnsTipoDocumentoDto } from './lib/cmns-tipo-documento.interface';
export type { ICmnsTipoEmail } from './lib/cmns-tipo-email.interface';
export { CmnsTipoEmailDto } from './lib/cmns-tipo-email.interface';
export type { ICmnsTipoEndereco } from './lib/cmns-tipo-endereco.interface';
export { CmnsTipoEnderecoDto } from './lib/cmns-tipo-endereco.interface';
export type { ICmnsTipoTelefone } from './lib/cmns-tipo-telefone.interface';
export { CmnsTipoTelefoneDto } from './lib/cmns-tipo-telefone.interface';
