import { CmnsPais } from './cmns-pais.entity';
import { CmnsUnidadeFederativa } from './cmns-unidade-federativa.entity';
import { CmnsLocalidade } from './cmns-localidade.entity';
import { CmnsBairro } from './cmns-bairro.entity';
import { CmnsLogradouro } from './cmns-logradouro.entity';
import { CmnsCargo } from './cmns-cargo.entity';
import { CmnsNacionalidade } from './cmns-nacionalidade.entity';
import {  } from './cmns-orgao-expedidor.entity';
import { } from './cmns-profissao.entity';
import { } from './cmns-ramo-atividade.entity';
import { } from './cmns-tipo-documento.entity';
import { } from './cmns-tipo-email.entity';
import { } from './cmns-tipo-endereco.entity';
import { } from './cmns-tipo-telefone.entity';
import { } from './cmns-pessoa.entity';
import { } from './cmns-pessoa-documento.entity';
import { } from './cmns-pessoa-email.entity';
import { } from './cmns-pessoa-endereco.entity';
import { } from './cmns-pessoa-fisica.entity';
import { } from './cmns-pessoa-imagem.entity';
import { } from './cmns-pessoa-juridica.entity';
import { } from './cmns-pessoa-telefone.entity';
import { } from './cmns-usuario.entity';
import { } from './cmns-grupo-usuario.entity';
import { } from './cmns-unem-usuario.entity';
