export * from './lib/cmns-interfaces.module';
export type {ICmnsBairro, CmnsBairroDto} from './lib/cmns-bairro.interface';
export type {ICmnsPais, CmnsPaisDto } from './lib/cmns-pais.interface';
export type {ICmnsUnidadeFederativa, CmnsUnidadeFederativaDto} from './lib/cmns-unidade-federativa.interface';
export type {ICmnsLocalidade, CmnsLocalidadeDto} from './lib/cmns-localidade.interface';
export type {ICmnsLogradouro, CmnsLogradouroDto} from './lib/cmns-logradouro.interface';
export type {ICmnsCargo, CmnsCargoDto} from './lib/cmns-cargo.interface';
export type {ICmnsNacionalidade, CmnsNacionalidadeDto } from './lib/cmns-nacionalidade.interface';
export type {ICmnsOrgaoExpedidor, CmnsOrgaoExpedidorDto} from './lib/cmns-orgao-expedidor.interface';
export type {ICmnsProfissao, CmnsProfissaoDto} from './lib/cmns-profissao.interface';
export type {ICmnsRamoAtividade, CmnsRamoAtividadeDto} from './lib/cmns-ramo-atividade.interface';
export type {ICmnsTipoDocumento, CmnsTipoDocumentoDto} from './lib/cmns-tipo-documento.interface';
export type {ICmnsTipoEmail, CmnsTipoEmailDto} from './lib/cmns-tipo-email.interface';
export type {ICmnsTipoEndereco, CmnsTipoEnderecoDto} from './lib/cmns-tipo-endereco.interface';
export type {ICmnsTipoTelefone, CmnsTipoTelefoneDto} from './lib/cmns-tipo-telefone.interface';
export type {ICmnsPessoa, CmnsPessoaDto} from './lib/cmns-pessoa.interface';
export type {ICmnsPessoaDocumento, CmnsPessoaDocumentoDto} from './lib/cmns-pessoa-documento.interface';
export type {ICmnsPessoaEmail, CmnsPessoaEmailDto} from './lib/cmns-pessoa-email.interface';
export type {ICmnsPessoaEndereco, CmnsPessoaEnderecoDto} from './lib/cmns-pessoa-endereco.interface';
export type {ICmnsPessoaFisica, CmnsPessoaFisicaDto} from './lib/cmns-pessoa-fisica.interface';
export type {ICmnsPessoaImagem, CmnsPessoaImagemDto} from './lib/cmns-pessoa-imagem.interface';
export type {ICmnsPessoaJuridica, CmnsPessoaJuridicaDto} from './lib/cmns-pessoa-juridica.interface';
export type {ICmnsPessoaTelefone, CmnsPessoaTelefoneDto}from './lib/cmns-pessoa-telefone.interface';
export type {ICmnsGrupoUsuario, CmnsGrupoUsuarioDto} from './lib/cmns-grupo-usuario.interface';
export type {ICmnsUsuario, CmnsUsuarioDto} from './lib/cmns-usuario.interface';

